version: '2'
services:
  db:
    image: 'postgres:9.6.2-alpine'
    environment:
      - POSTGRES_PASSWORD=654321
    expose:
      - '5432'
  lime:
    image: 'mariomourao/docker-limesurvey'
    links:
      - db
    ports:
      - '80:80'